-- NEXO: asignación definitiva PRODUCTO -> PROVEEDOR
-- Fuente: Excel PEDIDOS COCINA / DESAYUNOS
-- No modifica productos.proveedor. La relación canónica se guarda en productos_proveedores.
-- PATATAS SANZ se integra en Eduardo Sanz (18).

BEGIN;

-- Crear solo los proveedores que faltasen. No duplica los existentes.
INSERT INTO proveedores (nombre)
VALUES
    ('Panadería La Familia'),,
    ('DIST. LA COMPAÑÍA')
ON CONFLICT (nombre) DO NOTHING;

-- Reemplaza/asigna el proveedor del producto según el bloque real del Excel.
WITH mapa(producto, proveedor) AS (
    ('ANCHOA 00 CASA SANTOÑA', 'Norteños'),
    ('CALLOS PRECOCINADOS 1 KG (ROGUSA)', 'Norteños'),
    ('CENTRO PALETA CEBO CAMPO IB 50%', 'Norteños'),
    ('FILETES CACHOPO TERNERA', 'Norteños'),
    ('LOMO ALTO VACA S/H PREMIUM', 'Norteños'),
    ('LOMO BAJO VACA S/H PREMIUM', 'Norteños'),
    ('PALETILLA DE LECHAL CONFITADA A BAJA TEMPERATURA', 'Norteños'),
    ('QUESO IDIAZABAL ETXEGARAY', 'Norteños'),
    ('SALSA TARTUFATA', 'Norteños'),
    ('SOLOMILLO VACA NACIONAL', 'Norteños'),
    ('LOMO NEGRO', 'Petaca Chico'),
    ('PLATO (LINGOTES 8 CM)', 'Petaca Chico'),
    ('DESCARGAMENTO (SAKU)', 'Petaca Chico'),
    ('RECORTES / SANGANCHO', 'Petaca Chico'),
    ('PARPATANA (SIN HUESO)', 'Petaca Chico'),
    ('CHISTORRA DE ATUN', 'Petaca Chico'),
    ('CARBON VEGETAL GREY E HOSTELERIA', 'Carbosur'),
    ('MINI BOLLITOS DE PAN', 'Panadería La Familia'),
    ('HAMBURGUESA GRANDE SIN SESAMO', 'Grupo Viena'),
    ('MOLLETE CRISTAL', 'Grupo Viena'),
    ('PAN DE MOLDE BRIOCHE', 'Grupo Viena'),
    ('MINI HOGACITAS BLANCAS', 'Grupo Viena'),
    ('MINI MINI CHATO (BRIOCHE', 'Grupo Viena'),
    ('PAN DE MAIZ', 'Grupo Viena'),
    ('PAN DE PASAS', 'Grupo Viena'),
    ('PAN CHAPATA BARRA', 'Grupo Viena'),
    ('LINGOTE COCHINILLO SEGOVIA', 'Distribuciones Plata'),
    ('HAMBURGUESA DE COCHINILLO', 'Distribuciones Plata'),
    ('PANECILLO S/GLUTEN BETINA 45 UD', 'Berlys Monbake Bollería'),
    ('MINI ENSAIMADA PLUS  BERLYS 72 UD', 'Berlys Monbake Bollería'),
    ('GUACAMOLE CASERO', 'Los Cursos'),
    ('PRESA SAN PASCUAL', 'Jamonzar'),
    ('JAMONES RESERVA 30 MESES', 'Jamonzar'),
    ('SALCHICHON', 'Jamonzar'),
    ('CHORIZO', 'Jamonzar'),
    ('QUESO DE CERDO', 'Jamonzar'),
    ('DISCO PIMIENTA 50 g / 6 u /', 'Colmado Singular'),
    ('KETCHUP BLOODY MARY 250 g / 6 u', 'Colmado Singular'),
    ('PAN GUTTIATO 1 Kg / Ud (caja 3 Uds)', 'Colmado Singular'),
    ('PEPINILLOS BURGER 400GR /12 UDS', 'Colmado Singular'),
    ('ACEITE VIRGEN EXTRA 5L', 'Aceites Majen'),
    ('ACEITE VIRGEN 5L', 'Aceites Majen'),
    ('ACEITE ORUJO 5L', 'Aceites Majen'),
    ('BOTELLA AOVE PICUAL 500ML', 'Aceites Majen'),
    ('BOTELLA AOVE ARBEQUINO 500ML', 'Aceites Majen'),
    ('BOTELLA AOVE ECOLOGICO 500ML', 'Aceites Majen'),
    ('ACEITE GIRASOL 1L', 'Aceites Majen'),
    ('PATATA BASTON CON PIEL', 'Eduardo Sanz'),
    ('PATATA ROJA (ENSALADILLA)', 'Eduardo Sanz'),
    ('PATATA AGRIA LAVADA (P.GAJO)', 'Eduardo Sanz'),
    ('AJO PELADO', 'Eduardo Sanz'),
    ('PATATA PANADERA', 'Eduardo Sanz'),
    ('ALCACHOFAS CONF FLOR 20UD', 'Rama y Sarmiento'),
    ('CARNE ALCACHOFA CONF', 'Rama y Sarmiento'),
    ('PUERROS CONF', 'Rama y Sarmiento'),
    ('BOX MOSCATEL 15L', 'Rama y Sarmiento'),
    ('5 LOMOS BACALAO DESALADO 200GRS BANDEJA', 'Bacalao Barquero'),
    ('TUBER MELANOSPORUM - SEGUNDA (TRUFA)', 'MyTruff'),
    ('CARNE BURGUER PAJUNA', 'Cárnicas Luján'),
    ('CORDERO SEGUREÑO (CUELLO)', 'Cárnicas Luján'),
    ('BACALAO CARTA', 'Jesús Tojar'),
    ('CERDO CABEZADA', 'Jesús Tojar'),
    ('CERDO COSTILLAS', 'Jesús Tojar'),
    ('CERDO LOMO CINTA FILETEADA', 'Jesús Tojar'),
    ('CERDO LONGANIZA F', 'Jesús Tojar'),
    ('CERDO MORCILLA DULCE', 'Jesús Tojar'),
    ('CERDO PALETILLA', 'Jesús Tojar'),
    ('CERDO PALETILLA PICADA', 'Jesús Tojar'),
    ('CERDO PALETILLA TROCEADA', 'Jesús Tojar'),
    ('CERDO PANCETA FRESCA', 'Jesús Tojar'),
    ('CINTA LOMO', 'Jesús Tojar'),
    ('HUESO BLANCO', 'Jesús Tojar'),
    ('HUESO JAMON', 'Jesús Tojar'),
    ('HUEVOS L FRESCOS', 'Jesús Tojar'),
    ('LANGOSTINOS COLAS', 'Jesús Tojar'),
    ('NARANJAS ZUMO F', 'Jesús Tojar'),
    ('POLLO CHURRASCO C/ PIEL', 'Jesús Tojar'),
    ('POLLO CHURRASCO S/PIEL', 'Jesús Tojar'),
    ('POLLO PECHUGA  F', 'Jesús Tojar'),
    ('TOMATE PERA', 'Jesús Tojar'),
    ('ESPINACAS CONGELADAS', 'Jesús Tojar'),
    ('ACEITE SESAMO', 'Makro'),
    ('AJO NEGRO', 'Makro'),
    ('ALBAHACA (FRESCA)', 'Makro'),
    ('ALCAPARRAS', 'Makro'),
    ('ALMENDRAS CRUDAS', 'Makro'),
    ('AROMA VAINILLA VAHINE 200ML (REPOSTERIA)', 'Makro'),
    ('AZAFRAN', 'Makro'),
    ('BICARBONATO 1KG (REPOSTERIA)', 'Makro'),
    ('BROCHETA MADERA ESPETO', 'Makro'),
    ('CACAO PURO VALOR DESGR 750GR(REPOSTERIA)', 'Makro'),
    ('CEBOLLA CHALOTA FRANCESA', 'Makro'),
    ('CEBOLLINO (FRESCO)', 'Makro'),
    ('CLARA HUEVO METRO CHEF (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE BLANCO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE NEGRO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE C/LECHE TABLETA (REPOSTERIA)', 'Makro'),
    ('METRO CHEF COBERTURA GOTA 72%2.5KG (REPOSTERIA)', 'Makro'),
    ('COULANT CHOCOLATE', 'Makro'),
    ('GALLETA PICA TOPPING OREO (REPOSTERIA)', 'Makro'),
    ('GELATINA IGGY''S  6 LAMINAS X10 60G (REPOSTERIA)', 'Makro'),
    ('GUANCIALE', 'Makro'),
    ('HIERBABUENA FRECA', 'Makro'),
    ('HUEVO LIQUIDO', 'Makro'),
    ('JAMON COCIDO EXTRA (DESAYUNOS)', 'Makro'),
    ('LEVADURA POLVO (REPOSTERIA)', 'Makro'),
    ('LEVADURA SECA 500GR (REPOSTERIA)', 'Makro'),
    ('LIMAS', 'Makro'),
    ('MAIZENA EXPRES', 'Makro'),
    ('MARGARINA MC  BLOQUE 5KG (REPOSTERIA)', 'Makro'),
    ('NARANJA DESHIDRATADA (CITROMAX)', 'Makro'),
    ('NATA SPRAY', 'Makro'),
    ('NATA MONTAR LA ASTURIANA 1LT (REPOSTERIA)', 'Makro'),
    ('NUECES BORGES (REPOSTERIA)', 'Makro'),
    ('PAN RALLADO EL MOLINO', 'Makro'),
    ('PASAS ITAC', 'Makro'),
    ('PASTA FILO', 'Makro'),
    ('PATE IBERICO LATA 700GR (DESAYUNOS)', 'Makro'),
    ('PAVO BARRA  (DESAYUNOS)', 'Makro'),
    ('PEDRO XIMENEZ', 'Makro'),
    ('PEPINILLOS EN VINAGRE', 'Makro'),
    ('PIMIENTOS DE COLORES', 'Makro'),
    ('PIPARRA SARASA', 'Makro'),
    ('PIPAS PELADAS DE CALABAZA', 'Makro'),
    ('PULPA PIMIENTO CHORICERO', 'Makro'),
    ('PUNTAS DE FOIE CONGELADAS BOLSA', 'Makro'),
    ('MASCARPONE', 'Makro'),
    ('QUESO CURADO', 'Makro'),
    ('QUESO EDAMM BARRA (DESAYUNOS)', 'Makro'),
    ('QUESO ROQUEFORT CREMA LA FUENTE TARRINA 500G (DESAYUNOS)', 'Makro'),
    ('SAL MALDON', 'Makro'),
    ('SALSA CHIMICHURRI', 'Makro'),
    ('SALSA KETCHUP', 'Makro'),
    ('SALSA MOSTAZA', 'Makro'),
    ('SALSA SOJA', 'Makro'),
    ('SALSA TABASCO', 'Makro'),
    ('SOBRASADA IBERICA EL POZO TARRINA 250G (DESAYUNOS)', 'Makro'),
    ('TOMILLO FRESCO', 'Makro'),
    ('YEMA HUEVO', 'Makro'),
    ('YOGURT GRIEGO', 'Makro'),
    ('PIMIENTOS LATA CORTADOS (TAPA)', 'Makro'),
    ('PULPA DE PIÑA', 'Makro'),
    ('HUEVOS CODORNIZ', 'Makro'),
    ('HELADO VAINILLA', 'Makro'),
    ('ARROZ ARBORIO', 'Makro'),
    ('WANTON CONGELADO', 'Makro'),
    ('FRUTAS DEL BOSQUE CONGELADAS', 'Makro'),
    ('PURE CONGELADO MARACUYA', 'Makro'),
    ('TOMATE SECO EN ACEITE', 'Makro'),
    ('PAPEL SULFURIZADO MARRON (GLOVO)', 'Makro'),
    ('CARRILERRA IBERICAS', 'Makro'),
    ('HELADO BIO CHOCOLATE', 'Pole Sud'),
    ('HELADO BIO VAINILLA', 'Pole Sud'),
    ('HELADO BIO VIOLETAS', 'Pole Sud'),
    ('QUESO AÑEJO', 'Quesos Levasa'),
    ('LINGOTE MANTEQUILLA OVEJA 2,5KG (REPOSTERIA)', 'Quesos Calaveruela'),
    ('ACEITE GIRASOL', 'Distribución Sandi'),
    ('AZUCAR BLANQUILLA (REPOSTERIA)', 'Distribución Sandi'),
    ('BOLSA ÑORAS ENTERAS TRIUNFADOR', 'Distribución Sandi'),
    ('BOTE AJI TRITURADO INDUSTRIAL***', 'Distribución Sandi'),
    ('BOTE AJONJOLI DORADO EXTRA INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE CANELA RAMA  EXTRA IND.', 'Distribución Sandi'),
    ('BOTE CONDIMENTO AMARILLO IND.', 'Distribución Sandi'),
    ('BOTE CURRY INGLES INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE ESPECIAS RAS EL HANUT', 'Distribución Sandi'),
    ('BOTE LAUREL RAMA IND.', 'Distribución Sandi'),
    ('BOTE MIEL RAMIFLOR', 'Distribución Sandi'),
    ('BOTE NUEZ MOSCADA MOLIDA IND.', 'Distribución Sandi'),
    ('BOTE OREGANO INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE PIMENTON MOLIDO DULCE', 'Distribución Sandi'),
    ('BOTE PIMIENTA MOLIDA BLANCA IND.', 'Distribución Sandi'),
    ('BOTE TOMILLO HOJA INDUSTRIAL', 'Distribución Sandi'),
    ('BOTELLA ACEITE GIRASOL 1L', 'Distribución Sandi'),
    ('BOTELLA VINAGRE DE VINO  MERRY', 'Distribución Sandi'),
    ('BOVRIL', 'Distribución Sandi'),
    ('BRIK CALDO DE PESCADO', 'Distribución Sandi'),
    ('BRIK CALDO DE POLLO G.BLANCA', 'Distribución Sandi'),
    ('BRIK CALDO VEGETAL G. BLANCA', 'Distribución Sandi'),
    ('CAJA AZUCAR MORENO BOLSITAS 100 U.', 'Distribución Sandi'),
    ('CHAMPIÑON LAMINADO', 'Distribución Sandi'),
    ('HARINA DE TRIGO (REPOSTERIA)', 'Distribución Sandi'),
    ('LATA ATUN ISABEL R0-400 A.VEGETAL A/F', 'Distribución Sandi'),
    ('LATA ATUN TRONCO HOST. 1KG (DESAYUNOS)', 'Distribución Sandi'),
    ('PAQ. ESPECIAS PINCHITOS RUCA', 'Distribución Sandi'),
    ('PAQ. SEMOLA DE TRIGO MOLINO', 'Distribución Sandi'),
    ('PAQUETE HARINA FUERZA GALLO', 'Distribución Sandi'),
    ('RETRACTIL SAL LEDA', 'Distribución Sandi'),
    ('T- GARBANZOS COCIDOS PEDRIZA', 'Distribución Sandi'),
    ('T- MERMELADA MELOCOTON HELIOS 4K (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO ALUBIAS COCIDAS DIAMIR', 'Distribución Sandi'),
    ('TARRO ALUBIAS COCIDAS LUENGO', 'Distribución Sandi'),
    ('TARRO MERMELADA FRESA BEBE 370 GR (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO MIEL DE CAÑA', 'Distribución Sandi'),
    ('TOMATE FRITO ORLANDO', 'Distribución Sandi'),
    ('VINO BLANCO BRIK G. DUQUE', 'Distribución Sandi'),
    ('BOBINA ALUMINIO INDUSTRIAL VILEDA', 'Distribución Sandi'),
    ('BOBINA MECHA COLHOGAR (TORK)', 'Distribución Sandi'),
    ('BOTELLA FAIRY', 'Distribución Sandi'),
    ('CAJA HIGIENICO GOFRADO STRONG 202 MTR', 'Distribución Sandi'),
    ('CAJA IMPRESAS PLIEGUE AMERICANO SANCHO ORIG', 'Distribución Sandi'),
    ('CAJA IMPRESAS SANCHO ORIGINAL 20X20 BLANCAS', 'Distribución Sandi'),
    ('CAJA SECAMANOS STRONG 155 MTRS.', 'Distribución Sandi'),
    ('CAJA SERVILLETAS MINI BARRA EXCEL 9', 'Distribución Sandi'),
    ('CAJA SERVILLETAS MINI IMPRESAS', 'Distribución Sandi'),
    ('CEPILLO GRANDE EXTRA', 'Distribución Sandi'),
    ('CUCHARAS PLASTICO', 'Distribución Sandi'),
    ('ENVASES BISAGRA OPS 500 C.C. NUPIK', 'Distribución Sandi'),
    ('ESTROPAJO METALICO INOX 40 GR', 'Distribución Sandi'),
    ('ESTROPAJO SALVAUÑAS VILEDA', 'Distribución Sandi'),
    ('FILM TRANSPARENTE VILEDA 30X300 M', 'Distribución Sandi'),
    ('GARRAFA LEJIA ALVASA APTA ALIM.', 'Distribución Sandi'),
    ('GUANTES NITRILO M (100 U)', 'Distribución Sandi'),
    ('HIGIENICO INDUSTRIAL CANUTO ANCHO', 'Distribución Sandi'),
    ('LAVAVAJILLAS SUTTER UNIVERSAL PLUS', 'Distribución Sandi'),
    ('LEJIA', 'Distribución Sandi'),
    ('PAJITAS ART. ENFUNDADAS ARTICULADAS', 'Distribución Sandi'),
    ('PALO CEPILLO VILEDA 1.40 METROS', 'Distribución Sandi'),
    ('PAPEL SILICONADO HORNO (500UDS)', 'Distribución Sandi'),
    ('PAQ. BOLSAS BLOCK 25X35+3', 'Distribución Sandi'),
    ('PAQUETE BOLSAS ASA 40X50', 'Distribución Sandi'),
    ('PAQUETE ENVASES BISAGRA 1,5 L', 'Distribución Sandi'),
    ('PORTA-MECHA DISPENSADOR BLANCO LOSDI', 'Distribución Sandi'),
    ('RECAMBIO FREGONA ALG. EXTRAL. PLA', 'Distribución Sandi'),
    ('ROLLO BAYETA VILEDA UNIV. 8 MTRS', 'Distribución Sandi'),
    ('ROLLO BOLSAS BASURA IND EXT 90X105', 'Distribución Sandi'),
    ('ROLLO PAÑO BLANCO', 'Distribución Sandi'),
    ('ROLLO PAPEL COCINA', 'Distribución Sandi'),
    ('ROLLO REGISTRADORA 75X80X12', 'Distribución Sandi'),
    ('ROLLO TERMICO 80X80X12 **', 'Distribución Sandi'),
    ('SALLOSPHERE EXTREME COCINAS', 'Distribución Sandi'),
    ('TARRINAS BISAG PET 500 CC', 'Distribución Sandi'),
    ('BOLLO MANTEQUILLA BERLYS  24UD', 'Berlys Monbake Bollería'),
    ('BOLLO SUIZO MANTEQUILLA MONBAKE 30 UD', 'Berlys Monbake Bollería'),
    ('CROISSANT CURVO GOURMET 100G 46 UD', 'Berlys Monbake Bollería'),
    ('CROISSANT PLUS RECTO 80GR  BERLYS 52 UD', 'Berlys Monbake Bollería'),
    ('ENSAIMADA PLUS 90 GR 36 UD', 'Berlys Monbake Bollería'),
    ('TORRIJA PAN BRIOCHE BERTIZ 30 UD', 'Berlys Monbake Bollería'),
    ('TRENZA NUECES Y PASAS TRADICION KORGEST 1UD', 'Berlys Monbake Bollería'),
    ('PAN BRIOCHE JUANITO REBEL ROLLS 54 GR', 'Distribuciones Plata'),
    ('ACEITE OLIVA VIRGEN EXTRA NAVARRO GARCIA 5L', 'DIST. LA COMPAÑÍA'),
    ('JAMON COCIDO EXTRA (DESAYUNOS)', 'Makro'),
    ('PATE IBERICO LATA 700GR (DESAYUNOS)', 'Makro'),
    ('PAVO BARRA  (DESAYUNOS)', 'Makro'),
    ('QUESO EDAMM BARRA (DESAYUNOS)', 'Makro'),
    ('QUESO ROQUEFORT CREMA LA FUENTE TARRINA 500G (DESAYUNOS)', 'Makro'),
    ('SOBRASADA IBERICA EL POZO TARRINA 250G (DESAYUNOS)', 'Makro'),
    ('AROMA VAINILLA VAHINE 200ML (REPOSTERIA)', 'Makro'),
    ('ACOR AZUCAR GLACE 500G MK (REPOSTERIA)', 'Makro'),
    ('ACOR AZUCAR MORENO 1KG (REPOSTERIA)', 'Makro'),
    ('BICARBONATO 1KG (REPOSTERIA)', 'Makro'),
    ('CACAO PURO VALOR DESGR 750GR(REPOSTERIA)', 'Makro'),
    ('CLARA HUEVO METRO CHEF (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE BLANCO NESTLE POSTRES (REPOSTERIA) 170GR', 'Makro'),
    ('CHOCOLATE BLANCO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE NEGRO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE C/LECHE TABLETA (REPOSTERIA)', 'Makro'),
    ('METRO CHEF COBERTURA GOTA 72%2.5KG (REPOSTERIA)', 'Makro'),
    ('DULCE DE LECHE MARDEL 1KG (REPOSTERIA)', 'Makro'),
    ('GALLETA MARIA DORADA 200GR (REPOSTERIA)', 'Makro'),
    ('GALLETA PICA TOPPING OREO (REPOSTERIA)', 'Makro'),
    ('GELATINA IGGY''S  6 LAMINAS X10 60G (REPOSTERIA)', 'Makro'),
    ('LEVADURA POLVO (REPOSTERIA)', 'Makro'),
    ('LEVADURA SECA 500GR (REPOSTERIA)', 'Makro'),
    ('MARGARINA MC  BLOQUE 5KG (REPOSTERIA)', 'Makro'),
    ('NATA MONTAR LA ASTURIANA 1LT (REPOSTERIA)', 'Makro'),
    ('NUECES BORGES (REPOSTERIA)', 'Makro'),
    ('LATA ATUN TRONCO HOST. 1KG (DESAYUNOS)', 'Distribución Sandi'),
    ('T- MERMELADA MELOCOTON HELIOS 4K (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO MERMELADA FRESA BEBE 370 GR (DESAYUNOS)', 'Distribución Sandi'),
    ('CAJA SERVILLETAS PLATO TOSTADAS 140UD', 'Distribución Sandi'),
    ('AZUCAR BLANQUILLA (REPOSTERIA)', 'Distribución Sandi'),
    ('HARINA REPOSTERIA GALLO (REPOSTERIA)', 'Distribución Sandi'),
    ('HARINA DE TRIGO (REPOSTERIA)', 'Distribución Sandi'),
    ('PLATANOS NORMALES (REPOSTERIA)', 'Isidro verduleria'),
    ('PLATANOS MADUROS (REPOSTERIA)', 'Isidro verduleria'),
    ('ZANAHORIA - REPOSTERIA', 'Isidro verduleria'),
    ('LINGOTE MANTEQUILLA OVEJA 2,5KG (REPOSTERIA)', 'Quesos Calaveruela')
)
INSERT INTO productos_proveedores (producto_id, proveedor_id)
SELECT
    p.id,
    pr.id
FROM mapa m
JOIN productos p
    ON regexp_replace(UPPER(TRIM(p.nombre)), '\s+', ' ', 'g')
     = regexp_replace(UPPER(TRIM(m.producto)), '\s+', ' ', 'g')
JOIN proveedores pr
    ON regexp_replace(UPPER(TRIM(pr.nombre)), '\s+', ' ', 'g')
     = regexp_replace(UPPER(TRIM(m.proveedor)), '\s+', ' ', 'g')
ON CONFLICT (producto_id)
DO UPDATE SET proveedor_id = EXCLUDED.proveedor_id;

COMMIT;

-- VALIDACIÓN: productos del Excel que no encontraron coincidencia en productos.
WITH mapa(producto, proveedor) AS (
    ('ANCHOA 00 CASA SANTOÑA', 'Norteños'),
    ('CALLOS PRECOCINADOS 1 KG (ROGUSA)', 'Norteños'),
    ('CENTRO PALETA CEBO CAMPO IB 50%', 'Norteños'),
    ('FILETES CACHOPO TERNERA', 'Norteños'),
    ('LOMO ALTO VACA S/H PREMIUM', 'Norteños'),
    ('LOMO BAJO VACA S/H PREMIUM', 'Norteños'),
    ('PALETILLA DE LECHAL CONFITADA A BAJA TEMPERATURA', 'Norteños'),
    ('QUESO IDIAZABAL ETXEGARAY', 'Norteños'),
    ('SALSA TARTUFATA', 'Norteños'),
    ('SOLOMILLO VACA NACIONAL', 'Norteños'),
    ('LOMO NEGRO', 'Petaca Chico'),
    ('PLATO (LINGOTES 8 CM)', 'Petaca Chico'),
    ('DESCARGAMENTO (SAKU)', 'Petaca Chico'),
    ('RECORTES / SANGANCHO', 'Petaca Chico'),
    ('PARPATANA (SIN HUESO)', 'Petaca Chico'),
    ('CHISTORRA DE ATUN', 'Petaca Chico'),
    ('CARBON VEGETAL GREY E HOSTELERIA', 'Carbosur'),
    ('MINI BOLLITOS DE PAN', 'Panadería La Familia'),
    ('HAMBURGUESA GRANDE SIN SESAMO', 'Grupo Viena'),
    ('MOLLETE CRISTAL', 'Grupo Viena'),
    ('PAN DE MOLDE BRIOCHE', 'Grupo Viena'),
    ('MINI HOGACITAS BLANCAS', 'Grupo Viena'),
    ('MINI MINI CHATO (BRIOCHE', 'Grupo Viena'),
    ('PAN DE MAIZ', 'Grupo Viena'),
    ('PAN DE PASAS', 'Grupo Viena'),
    ('PAN CHAPATA BARRA', 'Grupo Viena'),
    ('LINGOTE COCHINILLO SEGOVIA', 'Distribuciones Plata'),
    ('HAMBURGUESA DE COCHINILLO', 'Distribuciones Plata'),
    ('PANECILLO S/GLUTEN BETINA 45 UD', 'Berlys Monbake Bollería'),
    ('MINI ENSAIMADA PLUS  BERLYS 72 UD', 'Berlys Monbake Bollería'),
    ('GUACAMOLE CASERO', 'Los Cursos'),
    ('PRESA SAN PASCUAL', 'Jamonzar'),
    ('JAMONES RESERVA 30 MESES', 'Jamonzar'),
    ('SALCHICHON', 'Jamonzar'),
    ('CHORIZO', 'Jamonzar'),
    ('QUESO DE CERDO', 'Jamonzar'),
    ('DISCO PIMIENTA 50 g / 6 u /', 'Colmado Singular'),
    ('KETCHUP BLOODY MARY 250 g / 6 u', 'Colmado Singular'),
    ('PAN GUTTIATO 1 Kg / Ud (caja 3 Uds)', 'Colmado Singular'),
    ('PEPINILLOS BURGER 400GR /12 UDS', 'Colmado Singular'),
    ('ACEITE VIRGEN EXTRA 5L', 'Aceites Majen'),
    ('ACEITE VIRGEN 5L', 'Aceites Majen'),
    ('ACEITE ORUJO 5L', 'Aceites Majen'),
    ('BOTELLA AOVE PICUAL 500ML', 'Aceites Majen'),
    ('BOTELLA AOVE ARBEQUINO 500ML', 'Aceites Majen'),
    ('BOTELLA AOVE ECOLOGICO 500ML', 'Aceites Majen'),
    ('ACEITE GIRASOL 1L', 'Aceites Majen'),
    ('PATATA BASTON CON PIEL', 'Eduardo Sanz'),
    ('PATATA ROJA (ENSALADILLA)', 'Eduardo Sanz'),
    ('PATATA AGRIA LAVADA (P.GAJO)', 'Eduardo Sanz'),
    ('AJO PELADO', 'Eduardo Sanz'),
    ('PATATA PANADERA', 'Eduardo Sanz'),
    ('ALCACHOFAS CONF FLOR 20UD', 'Rama y Sarmiento'),
    ('CARNE ALCACHOFA CONF', 'Rama y Sarmiento'),
    ('PUERROS CONF', 'Rama y Sarmiento'),
    ('BOX MOSCATEL 15L', 'Rama y Sarmiento'),
    ('5 LOMOS BACALAO DESALADO 200GRS BANDEJA', 'Bacalao Barquero'),
    ('TUBER MELANOSPORUM - SEGUNDA (TRUFA)', 'MyTruff'),
    ('CARNE BURGUER PAJUNA', 'Cárnicas Luján'),
    ('CORDERO SEGUREÑO (CUELLO)', 'Cárnicas Luján'),
    ('BACALAO CARTA', 'Jesús Tojar'),
    ('CERDO CABEZADA', 'Jesús Tojar'),
    ('CERDO COSTILLAS', 'Jesús Tojar'),
    ('CERDO LOMO CINTA FILETEADA', 'Jesús Tojar'),
    ('CERDO LONGANIZA F', 'Jesús Tojar'),
    ('CERDO MORCILLA DULCE', 'Jesús Tojar'),
    ('CERDO PALETILLA', 'Jesús Tojar'),
    ('CERDO PALETILLA PICADA', 'Jesús Tojar'),
    ('CERDO PALETILLA TROCEADA', 'Jesús Tojar'),
    ('CERDO PANCETA FRESCA', 'Jesús Tojar'),
    ('CINTA LOMO', 'Jesús Tojar'),
    ('HUESO BLANCO', 'Jesús Tojar'),
    ('HUESO JAMON', 'Jesús Tojar'),
    ('HUEVOS L FRESCOS', 'Jesús Tojar'),
    ('LANGOSTINOS COLAS', 'Jesús Tojar'),
    ('NARANJAS ZUMO F', 'Jesús Tojar'),
    ('POLLO CHURRASCO C/ PIEL', 'Jesús Tojar'),
    ('POLLO CHURRASCO S/PIEL', 'Jesús Tojar'),
    ('POLLO PECHUGA  F', 'Jesús Tojar'),
    ('TOMATE PERA', 'Jesús Tojar'),
    ('ESPINACAS CONGELADAS', 'Jesús Tojar'),
    ('ACEITE SESAMO', 'Makro'),
    ('AJO NEGRO', 'Makro'),
    ('ALBAHACA (FRESCA)', 'Makro'),
    ('ALCAPARRAS', 'Makro'),
    ('ALMENDRAS CRUDAS', 'Makro'),
    ('AROMA VAINILLA VAHINE 200ML (REPOSTERIA)', 'Makro'),
    ('AZAFRAN', 'Makro'),
    ('BICARBONATO 1KG (REPOSTERIA)', 'Makro'),
    ('BROCHETA MADERA ESPETO', 'Makro'),
    ('CACAO PURO VALOR DESGR 750GR(REPOSTERIA)', 'Makro'),
    ('CEBOLLA CHALOTA FRANCESA', 'Makro'),
    ('CEBOLLINO (FRESCO)', 'Makro'),
    ('CLARA HUEVO METRO CHEF (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE BLANCO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE NEGRO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE C/LECHE TABLETA (REPOSTERIA)', 'Makro'),
    ('METRO CHEF COBERTURA GOTA 72%2.5KG (REPOSTERIA)', 'Makro'),
    ('COULANT CHOCOLATE', 'Makro'),
    ('GALLETA PICA TOPPING OREO (REPOSTERIA)', 'Makro'),
    ('GELATINA IGGY''S  6 LAMINAS X10 60G (REPOSTERIA)', 'Makro'),
    ('GUANCIALE', 'Makro'),
    ('HIERBABUENA FRECA', 'Makro'),
    ('HUEVO LIQUIDO', 'Makro'),
    ('JAMON COCIDO EXTRA (DESAYUNOS)', 'Makro'),
    ('LEVADURA POLVO (REPOSTERIA)', 'Makro'),
    ('LEVADURA SECA 500GR (REPOSTERIA)', 'Makro'),
    ('LIMAS', 'Makro'),
    ('MAIZENA EXPRES', 'Makro'),
    ('MARGARINA MC  BLOQUE 5KG (REPOSTERIA)', 'Makro'),
    ('NARANJA DESHIDRATADA (CITROMAX)', 'Makro'),
    ('NATA SPRAY', 'Makro'),
    ('NATA MONTAR LA ASTURIANA 1LT (REPOSTERIA)', 'Makro'),
    ('NUECES BORGES (REPOSTERIA)', 'Makro'),
    ('PAN RALLADO EL MOLINO', 'Makro'),
    ('PASAS ITAC', 'Makro'),
    ('PASTA FILO', 'Makro'),
    ('PATE IBERICO LATA 700GR (DESAYUNOS)', 'Makro'),
    ('PAVO BARRA  (DESAYUNOS)', 'Makro'),
    ('PEDRO XIMENEZ', 'Makro'),
    ('PEPINILLOS EN VINAGRE', 'Makro'),
    ('PIMIENTOS DE COLORES', 'Makro'),
    ('PIPARRA SARASA', 'Makro'),
    ('PIPAS PELADAS DE CALABAZA', 'Makro'),
    ('PULPA PIMIENTO CHORICERO', 'Makro'),
    ('PUNTAS DE FOIE CONGELADAS BOLSA', 'Makro'),
    ('MASCARPONE', 'Makro'),
    ('QUESO CURADO', 'Makro'),
    ('QUESO EDAMM BARRA (DESAYUNOS)', 'Makro'),
    ('QUESO ROQUEFORT CREMA LA FUENTE TARRINA 500G (DESAYUNOS)', 'Makro'),
    ('SAL MALDON', 'Makro'),
    ('SALSA CHIMICHURRI', 'Makro'),
    ('SALSA KETCHUP', 'Makro'),
    ('SALSA MOSTAZA', 'Makro'),
    ('SALSA SOJA', 'Makro'),
    ('SALSA TABASCO', 'Makro'),
    ('SOBRASADA IBERICA EL POZO TARRINA 250G (DESAYUNOS)', 'Makro'),
    ('TOMILLO FRESCO', 'Makro'),
    ('YEMA HUEVO', 'Makro'),
    ('YOGURT GRIEGO', 'Makro'),
    ('PIMIENTOS LATA CORTADOS (TAPA)', 'Makro'),
    ('PULPA DE PIÑA', 'Makro'),
    ('HUEVOS CODORNIZ', 'Makro'),
    ('HELADO VAINILLA', 'Makro'),
    ('ARROZ ARBORIO', 'Makro'),
    ('WANTON CONGELADO', 'Makro'),
    ('FRUTAS DEL BOSQUE CONGELADAS', 'Makro'),
    ('PURE CONGELADO MARACUYA', 'Makro'),
    ('TOMATE SECO EN ACEITE', 'Makro'),
    ('PAPEL SULFURIZADO MARRON (GLOVO)', 'Makro'),
    ('CARRILERRA IBERICAS', 'Makro'),
    ('HELADO BIO CHOCOLATE', 'Pole Sud'),
    ('HELADO BIO VAINILLA', 'Pole Sud'),
    ('HELADO BIO VIOLETAS', 'Pole Sud'),
    ('QUESO AÑEJO', 'Quesos Levasa'),
    ('LINGOTE MANTEQUILLA OVEJA 2,5KG (REPOSTERIA)', 'Quesos Calaveruela'),
    ('ACEITE GIRASOL', 'Distribución Sandi'),
    ('AZUCAR BLANQUILLA (REPOSTERIA)', 'Distribución Sandi'),
    ('BOLSA ÑORAS ENTERAS TRIUNFADOR', 'Distribución Sandi'),
    ('BOTE AJI TRITURADO INDUSTRIAL***', 'Distribución Sandi'),
    ('BOTE AJONJOLI DORADO EXTRA INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE CANELA RAMA  EXTRA IND.', 'Distribución Sandi'),
    ('BOTE CONDIMENTO AMARILLO IND.', 'Distribución Sandi'),
    ('BOTE CURRY INGLES INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE ESPECIAS RAS EL HANUT', 'Distribución Sandi'),
    ('BOTE LAUREL RAMA IND.', 'Distribución Sandi'),
    ('BOTE MIEL RAMIFLOR', 'Distribución Sandi'),
    ('BOTE NUEZ MOSCADA MOLIDA IND.', 'Distribución Sandi'),
    ('BOTE OREGANO INDUSTRIAL', 'Distribución Sandi'),
    ('BOTE PIMENTON MOLIDO DULCE', 'Distribución Sandi'),
    ('BOTE PIMIENTA MOLIDA BLANCA IND.', 'Distribución Sandi'),
    ('BOTE TOMILLO HOJA INDUSTRIAL', 'Distribución Sandi'),
    ('BOTELLA ACEITE GIRASOL 1L', 'Distribución Sandi'),
    ('BOTELLA VINAGRE DE VINO  MERRY', 'Distribución Sandi'),
    ('BOVRIL', 'Distribución Sandi'),
    ('BRIK CALDO DE PESCADO', 'Distribución Sandi'),
    ('BRIK CALDO DE POLLO G.BLANCA', 'Distribución Sandi'),
    ('BRIK CALDO VEGETAL G. BLANCA', 'Distribución Sandi'),
    ('CAJA AZUCAR MORENO BOLSITAS 100 U.', 'Distribución Sandi'),
    ('CHAMPIÑON LAMINADO', 'Distribución Sandi'),
    ('HARINA DE TRIGO (REPOSTERIA)', 'Distribución Sandi'),
    ('LATA ATUN ISABEL R0-400 A.VEGETAL A/F', 'Distribución Sandi'),
    ('LATA ATUN TRONCO HOST. 1KG (DESAYUNOS)', 'Distribución Sandi'),
    ('PAQ. ESPECIAS PINCHITOS RUCA', 'Distribución Sandi'),
    ('PAQ. SEMOLA DE TRIGO MOLINO', 'Distribución Sandi'),
    ('PAQUETE HARINA FUERZA GALLO', 'Distribución Sandi'),
    ('RETRACTIL SAL LEDA', 'Distribución Sandi'),
    ('T- GARBANZOS COCIDOS PEDRIZA', 'Distribución Sandi'),
    ('T- MERMELADA MELOCOTON HELIOS 4K (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO ALUBIAS COCIDAS DIAMIR', 'Distribución Sandi'),
    ('TARRO ALUBIAS COCIDAS LUENGO', 'Distribución Sandi'),
    ('TARRO MERMELADA FRESA BEBE 370 GR (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO MIEL DE CAÑA', 'Distribución Sandi'),
    ('TOMATE FRITO ORLANDO', 'Distribución Sandi'),
    ('VINO BLANCO BRIK G. DUQUE', 'Distribución Sandi'),
    ('BOBINA ALUMINIO INDUSTRIAL VILEDA', 'Distribución Sandi'),
    ('BOBINA MECHA COLHOGAR (TORK)', 'Distribución Sandi'),
    ('BOTELLA FAIRY', 'Distribución Sandi'),
    ('CAJA HIGIENICO GOFRADO STRONG 202 MTR', 'Distribución Sandi'),
    ('CAJA IMPRESAS PLIEGUE AMERICANO SANCHO ORIG', 'Distribución Sandi'),
    ('CAJA IMPRESAS SANCHO ORIGINAL 20X20 BLANCAS', 'Distribución Sandi'),
    ('CAJA SECAMANOS STRONG 155 MTRS.', 'Distribución Sandi'),
    ('CAJA SERVILLETAS MINI BARRA EXCEL 9', 'Distribución Sandi'),
    ('CAJA SERVILLETAS MINI IMPRESAS', 'Distribución Sandi'),
    ('CEPILLO GRANDE EXTRA', 'Distribución Sandi'),
    ('CUCHARAS PLASTICO', 'Distribución Sandi'),
    ('ENVASES BISAGRA OPS 500 C.C. NUPIK', 'Distribución Sandi'),
    ('ESTROPAJO METALICO INOX 40 GR', 'Distribución Sandi'),
    ('ESTROPAJO SALVAUÑAS VILEDA', 'Distribución Sandi'),
    ('FILM TRANSPARENTE VILEDA 30X300 M', 'Distribución Sandi'),
    ('GARRAFA LEJIA ALVASA APTA ALIM.', 'Distribución Sandi'),
    ('GUANTES NITRILO M (100 U)', 'Distribución Sandi'),
    ('HIGIENICO INDUSTRIAL CANUTO ANCHO', 'Distribución Sandi'),
    ('LAVAVAJILLAS SUTTER UNIVERSAL PLUS', 'Distribución Sandi'),
    ('LEJIA', 'Distribución Sandi'),
    ('PAJITAS ART. ENFUNDADAS ARTICULADAS', 'Distribución Sandi'),
    ('PALO CEPILLO VILEDA 1.40 METROS', 'Distribución Sandi'),
    ('PAPEL SILICONADO HORNO (500UDS)', 'Distribución Sandi'),
    ('PAQ. BOLSAS BLOCK 25X35+3', 'Distribución Sandi'),
    ('PAQUETE BOLSAS ASA 40X50', 'Distribución Sandi'),
    ('PAQUETE ENVASES BISAGRA 1,5 L', 'Distribución Sandi'),
    ('PORTA-MECHA DISPENSADOR BLANCO LOSDI', 'Distribución Sandi'),
    ('RECAMBIO FREGONA ALG. EXTRAL. PLA', 'Distribución Sandi'),
    ('ROLLO BAYETA VILEDA UNIV. 8 MTRS', 'Distribución Sandi'),
    ('ROLLO BOLSAS BASURA IND EXT 90X105', 'Distribución Sandi'),
    ('ROLLO PAÑO BLANCO', 'Distribución Sandi'),
    ('ROLLO PAPEL COCINA', 'Distribución Sandi'),
    ('ROLLO REGISTRADORA 75X80X12', 'Distribución Sandi'),
    ('ROLLO TERMICO 80X80X12 **', 'Distribución Sandi'),
    ('SALLOSPHERE EXTREME COCINAS', 'Distribución Sandi'),
    ('TARRINAS BISAG PET 500 CC', 'Distribución Sandi'),
    ('BOLLO MANTEQUILLA BERLYS  24UD', 'Berlys Monbake Bollería'),
    ('BOLLO SUIZO MANTEQUILLA MONBAKE 30 UD', 'Berlys Monbake Bollería'),
    ('CROISSANT CURVO GOURMET 100G 46 UD', 'Berlys Monbake Bollería'),
    ('CROISSANT PLUS RECTO 80GR  BERLYS 52 UD', 'Berlys Monbake Bollería'),
    ('ENSAIMADA PLUS 90 GR 36 UD', 'Berlys Monbake Bollería'),
    ('TORRIJA PAN BRIOCHE BERTIZ 30 UD', 'Berlys Monbake Bollería'),
    ('TRENZA NUECES Y PASAS TRADICION KORGEST 1UD', 'Berlys Monbake Bollería'),
    ('PAN BRIOCHE JUANITO REBEL ROLLS 54 GR', 'Distribuciones Plata'),
    ('ACEITE OLIVA VIRGEN EXTRA NAVARRO GARCIA 5L', 'DIST. LA COMPAÑÍA'),
    ('JAMON COCIDO EXTRA (DESAYUNOS)', 'Makro'),
    ('PATE IBERICO LATA 700GR (DESAYUNOS)', 'Makro'),
    ('PAVO BARRA  (DESAYUNOS)', 'Makro'),
    ('QUESO EDAMM BARRA (DESAYUNOS)', 'Makro'),
    ('QUESO ROQUEFORT CREMA LA FUENTE TARRINA 500G (DESAYUNOS)', 'Makro'),
    ('SOBRASADA IBERICA EL POZO TARRINA 250G (DESAYUNOS)', 'Makro'),
    ('AROMA VAINILLA VAHINE 200ML (REPOSTERIA)', 'Makro'),
    ('ACOR AZUCAR GLACE 500G MK (REPOSTERIA)', 'Makro'),
    ('ACOR AZUCAR MORENO 1KG (REPOSTERIA)', 'Makro'),
    ('BICARBONATO 1KG (REPOSTERIA)', 'Makro'),
    ('CACAO PURO VALOR DESGR 750GR(REPOSTERIA)', 'Makro'),
    ('CLARA HUEVO METRO CHEF (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE BLANCO NESTLE POSTRES (REPOSTERIA) 170GR', 'Makro'),
    ('CHOCOLATE BLANCO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE NEGRO TABLETA (REPOSTERIA)', 'Makro'),
    ('CHOCOLATE C/LECHE TABLETA (REPOSTERIA)', 'Makro'),
    ('METRO CHEF COBERTURA GOTA 72%2.5KG (REPOSTERIA)', 'Makro'),
    ('DULCE DE LECHE MARDEL 1KG (REPOSTERIA)', 'Makro'),
    ('GALLETA MARIA DORADA 200GR (REPOSTERIA)', 'Makro'),
    ('GALLETA PICA TOPPING OREO (REPOSTERIA)', 'Makro'),
    ('GELATINA IGGY''S  6 LAMINAS X10 60G (REPOSTERIA)', 'Makro'),
    ('LEVADURA POLVO (REPOSTERIA)', 'Makro'),
    ('LEVADURA SECA 500GR (REPOSTERIA)', 'Makro'),
    ('MARGARINA MC  BLOQUE 5KG (REPOSTERIA)', 'Makro'),
    ('NATA MONTAR LA ASTURIANA 1LT (REPOSTERIA)', 'Makro'),
    ('NUECES BORGES (REPOSTERIA)', 'Makro'),
    ('LATA ATUN TRONCO HOST. 1KG (DESAYUNOS)', 'Distribución Sandi'),
    ('T- MERMELADA MELOCOTON HELIOS 4K (DESAYUNOS)', 'Distribución Sandi'),
    ('TARRO MERMELADA FRESA BEBE 370 GR (DESAYUNOS)', 'Distribución Sandi'),
    ('CAJA SERVILLETAS PLATO TOSTADAS 140UD', 'Distribución Sandi'),
    ('AZUCAR BLANQUILLA (REPOSTERIA)', 'Distribución Sandi'),
    ('HARINA REPOSTERIA GALLO (REPOSTERIA)', 'Distribución Sandi'),
    ('HARINA DE TRIGO (REPOSTERIA)', 'Distribución Sandi'),
    ('PLATANOS NORMALES (REPOSTERIA)', 'Isidro verduleria'),
    ('PLATANOS MADUROS (REPOSTERIA)', 'Isidro verduleria'),
    ('ZANAHORIA - REPOSTERIA', 'Isidro verduleria'),
    ('LINGOTE MANTEQUILLA OVEJA 2,5KG (REPOSTERIA)', 'Quesos Calaveruela')
)
SELECT m.producto, m.proveedor
FROM mapa m
LEFT JOIN productos p
    ON regexp_replace(UPPER(TRIM(p.nombre)), '\s+', ' ', 'g')
     = regexp_replace(UPPER(TRIM(m.producto)), '\s+', ' ', 'g')
WHERE p.id IS NULL
ORDER BY m.proveedor, m.producto;

-- VALIDACIÓN: asignaciones finales por proveedor.
SELECT
    pr.id AS proveedor_id,
    pr.nombre AS proveedor,
    COUNT(*) AS productos
FROM productos_proveedores pp
JOIN proveedores pr ON pr.id = pp.proveedor_id
GROUP BY pr.id, pr.nombre
ORDER BY pr.id;