ALTER TABLE productos
ADD COLUMN IF NOT EXISTS formato_compra VARCHAR(50);

ALTER TABLE productos
ADD COLUMN IF NOT EXISTS cantidad_formato NUMERIC(10,2);

ALTER TABLE productos
ADD COLUMN IF NOT EXISTS stock_minimo NUMERIC(10,2) DEFAULT 0;

ALTER TABLE productos
ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(100);
